"use client";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import React, { useState } from "react";
import { UserProvider} from "@/contexts/userContext";
import {onAuthStateChanged} from "firebase/auth"
import { auth } from "../firebase.config";
import { storeUserInfo } from "@/lib/utils";
import Cookies from "js-cookie";

onAuthStateChanged(auth, async (user) => {

  console.log("auth")

  const userDoesNotExist = Cookies.get("user") === null || Cookies.get("user") === undefined;
  
  console.log(user, "user from layout............")
  try {
    userDoesNotExist && user && user.emailVerified && await storeUserInfo(user);
  } catch (e) {
    console.log(e);
  }
})





// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   viewport: "width=device-width, initial-scale=1, maximum-scale=1 ",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <UserProvider>
        <body>
          <main>{children}</main>
          <Toaster />
        </body>
      </UserProvider>
    </html>
  );
}

// export default function Layout({ children }: LayoutProps) {

//   return (
//     <html lang="en">
//       <UserProvider>
//         <body className={inter.className}>
//           <UserContext.Provider value={{ user, setUser }}>
//             <main>{children}</main>
//             <Toaster />
//           </UserContext.Provider>
//         </body>
//       </UserProvider>
//     </html>
//   );
// }
